[project]
name = "galvatron-visualizer-vercel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "scipy>=1.13.1",
    "tqdm>=4.67.1",
]
